./eval.sh ../simple_example_update/AFWP/dll
./eval.sh ../simple_example_update/AFWP/sll
./eval.sh ../simple_example_update/avl
./eval.sh ../simple_example_update/binary_search_tree
./eval.sh ../simple_example_update/binomial_heap
./eval.sh ../simple_example_update/circular_list
./eval.sh ../simple_example_update/cyclist/aplas-stack
./eval.sh ../simple_example_update/cyclist/composite4
./eval.sh ../simple_example_update/cyclist/iter
./eval.sh ../simple_example_update/cyclist/schorr_waite
./eval.sh ../simple_example_update/dll
./eval.sh ../simple_example_update/glib_glist
./eval.sh ../simple_example_update/glib_gslist
./eval.sh ../simple_example_update/GRASShopper/dl
./eval.sh ../simple_example_update/GRASShopper/rec
./eval.sh ../simple_example_update/GRASShopper/sl
./eval.sh ../simple_example_update/GRASShopper/sls
./eval.sh ../simple_example_update/memory_region
./eval.sh ../simple_example_update/openbsd_queue
./eval.sh ../simple_example_update/prio_tree
./eval.sh ../simple_example_update/red_black_tree
./eval.sh ../simple_example_update/sll
./eval.sh ../simple_example_update/sortlist
./eval.sh ../simple_example_update/sv-comp/dll_of_dll
./eval.sh ../simple_example_update/sv-comp/rule_60_list
./eval.sh ../simple_example_update/tree_traversals
./eval.sh ../simple_example_update/tree_traversals/tree2list
./eval.sh ../simple_example_update/tree_traversals/tree2list_iter
